
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltchkppilnffytxakpva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0Y2hrcHBpbG5mZnl0eGFrcHZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA1ODMxMDQsImV4cCI6MjA5NjE1OTEwNH0.qisZ3xUMJLm5PUk7XFSv8OksoNARDDD9Sb9rarV2vGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
