
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtfrfhdblwrpmeyammwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0ZnJmaGRibHdycG1leWFtbXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA1ODUxMjcsImV4cCI6MjA5NjE2MTEyN30.PZ4jfh9IoIva6hp4_efaGUfe0lBRUuH-zcSjzMK3U7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
